# fly.toml app configuration file generated for portafolioliz on 2023-08-08T23:11:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "portafolioliz"
primary_region = "scl"

[[statics]]
  guest_path = "src" 
  url_prefix = "/" 
