# fly.toml app configuration file generated for portafolioliz on 2023-08-09T10:55:26-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "portafolioliz"
primary_region = "scl"

[build]

[[statics]]
  guest_path = "src"
  url_prefix = "/"
  
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]