
[build]
  api_version = "2"

[build.environment]
  NODE_VERSION = "14" 

[build]
  command = "ng build --prod"  
  publish = "dist/<my-first-project>"  n

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
